
{{- if semverCompare ">=1.16" (printf "%s.%s" .Capabilities.KubeVersion.Major (trimSuffix "+" .Capabilities.KubeVersion.Minor) )}}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta2
{{- end }}
kind: Deployment
metadata:
  name: stratos-fdbdoclayer
  labels:
    app: {{ template "fullname" . }}-fdbdoclayer
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ default 1 .Values.fdbdoclayerReplicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-fdbdoclayer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-fdbdoclayer
        release: {{ .Release.Name }}
    spec:
{{- with .Values.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      - name: fdbdoclayer
        image: {{.Values.kube.registry.hostname}}/{{.Values.kube.organization}}/{{ default "stratos-fdbdoclayer" .Values.images.fdbdoclayer}}:{{.Values.consoleVersion}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        env:
        - name: FDB_COORDINATOR
          value: {{ .Release.Name }}-fdbserver
        - name: CLUSTER_ID 
          value: chartdb:erlklkg
        - name: ENABLE_TLS
          value: "true"
        - name: SERVER_CRT
          value: "/etc/secrets/tls.crt"
        - name: SERVER_KEY
          value: "/etc/secrets/tls.key"
        - name: CA_CRT
          value: "/etc/secrets/ca.crt"      
        ports:
        - containerPort: 27016
        livenessProbe:
          tcpSocket:
            port: 27016
          initialDelaySeconds: 3
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 27016
          initialDelaySeconds: 3
          periodSeconds: 10
        volumeMounts:
        - name: certs
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: {{ .Release.Name }}-fdbdoclayer-certs
