
{{- if semverCompare ">=1.16" (printf "%s.%s" .Capabilities.KubeVersion.Major (trimSuffix "+" .Capabilities.KubeVersion.Minor) )}}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta2
{{- end }}
kind: Deployment
metadata:
  name: stratos-fdbserver
  labels:
    app: {{ template "fullname" . }}-fdbserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ default 1 .Values.fdbserverReplicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-fdbserver
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-fdbserver
        release: {{ .Release.Name }}
    spec:
{{- with .Values.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      - name: fdbserver
        image: {{.Values.kube.registry.hostname}}/{{.Values.kube.organization}}/{{ default "stratos-fdbserver" .Values.images.fdbserver}}:{{.Values.consoleVersion}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        env:
        - name: FDB_COORDINATOR
          value: {{ .Release.Name }}-fdbserver.{{ .Release.Namespace }}.svc.cluster.local
        - name: CLUSTER_ID
          value: chartdb:erlklkg
        ports:
        - containerPort: 4500
        livenessProbe:
          tcpSocket:
            port: 4500
          initialDelaySeconds: 3
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 4500
          initialDelaySeconds: 3
          periodSeconds: 10