
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fdbserver
  labels:
    app: {{ template "fullname" . }}-fdbserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
  - port: 4500
    targetPort: 4500
    protocol: TCP
    name: fdbserver
  selector:
    app: {{ template "fullname" . }}-fdbserver
    release: {{ .Release.Name }}